### ISSUE TITLE
blower control module

### ISSUE THREAD

**Issue by verityRF** [RespiraWorks/VentilatorSoftware#75]

**Comment by lee-matthews** [comment]
I'm thinking about changing the blower module to an actuator module, because there are other outputs too. A solenoid, and perhaps temperature control for the humidifier - what do you think?

**Comment by lee-matthews** [comment]
Never mind previous comment. I think I'll create a solenoid module, we could then maybe create an abstraction layer above that if necessary.

**Comment by martukas** [comment]
Make a ticket for the abstraction and put it in beta.

**Comment by jlebar** [comment]
pid.cpp controls the blower.  We might want to refactor, but does the fact that we have a module which controls the blower mean this is done?

**Comment by verityRF** [comment]
pid.cpp also had internal manual ways of creating sensor data, which is now put into a proper sensors.cpp. Blower needs to be put into its own module (which is still empty according to master right now). This is because other modules (aka sensors.cpp) have a dependency to be able to control/disable the blower to function 100% properly. 

I think lee was maybe working on this? Anyway it doesn't seem that hard since all it seems to involve is a single analogWrite.

**Comment by jlebar** [comment]
>  Blower needs to be put into its own module (which is still empty according to master right now). This is because other modules (aka sensors.cpp) have a dependency to be able to control/disable the blower to function 100% properly.

Got it.  I think it would be better to have a bug describing the functionality that's currently missing from those other modules -- if that's OK with you?  Then we can triage whether those  other bugs block alpha.

Going to close this; do you mind filing those other bugs (since I'm not sure what functionality is missing)?  If you disagree, feel free to reopen, no hard feelings, just trying to clean things up.
